steps:
  # Step 1: Detect changes in the vcomp folder
  - name: 'ubuntu'
    id: 'Check service vcomp'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep '^vcomp/'; then
          echo "Changes detected in vcomp"
          touch /workspace/service_vcomp.txt
        else
          echo "No changes in vcomp"
        fi

  # Step 2: Build the Docker image for vcomp
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build vcomp'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/vcomp:$COMMIT_SHA'
      - '-f'
      - './vcomp/Dockerfile'
      - './vcomp'
    waitFor: ['Check service vcomp']
    condition:
      fileExists: /workspace/service_vcomp.txt

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push vcomp'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/vcomp:$COMMIT_SHA'
    waitFor: ['Build vcomp']
    condition:
      fileExists: /workspace/service_vcomp.txt

  # Step 4: Deploy the vcomp service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy vcomp'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vcomp:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['Push vcomp']
    condition:
      fileExists: /workspace/service_vcomp.txt

# Specify a bucket for logs
logsBucket: "gs://vdocomp-logs"

substitutions:
  _SERVICE_NAME: 'vcomp'
  _REGION: 'asia-south1'
