steps:
  # Step 1: Detect changes in service1 (tts1 folder)
  - name: 'ubuntu'
    id: 'Check service1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if git diff --name-only $COMMIT_SHA~1 $COMMIT_SHA | grep '^tts1/'; then
          echo "Changes detected in tts1"
          touch /workspace/tts1.txt
        else
          echo "No changes in tts1"
        fi

  # Step 2: Build the Docker image for tts1
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build tts1'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tts1:$COMMIT_SHA'
      - '-f'
      - './tts1/Dockerfile'
      - './tts1'
    waitFor: ['Check service1']
    condition:
      fileExists: /workspace/service1.txt

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push tts1'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tts1:$COMMIT_SHA'
    waitFor: ['Build tts1']
    condition:
      fileExists: /workspace/service1.txt

  # Step 4: Deploy the service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy tts1'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tts1:$COMMIT_SHA'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['Push tts1']
    condition:
      fileExists: /workspace/service1.txt

# Specify a bucket for logs
logsBucket: "gs://vdocomp-logs"

substitutions:
  _SERVICE_NAME: 'tts1'
  _REGION: 'asia-south1'
